### ISSUE TITLE
Consider converting README.md to README.rst

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#49]
.. because pypi is not happy about markdown making the presentation of package ugly 😄 

See: https://pypi.org/project/PyWavefront/0.3.1/

**Comment by greenmoss** [comment]
Yeah, I knew about this one. Thanks 😄 . Primarily I did it in Markdown because I am lazy and didn't want to learn another markup language.

I see moves to make Markdown supported by Pypi. There's also a solution to embed a converter in the setup.py file. Again, mostly laziness has stopped me from pursuing this.

**Comment by einarf** [comment]
Think I found a lazy solution #51

**Comment by greenmoss** [comment]
Awesome, I'm glad they updated to support Markdown, thanks for looking!

**Comment by einarf** [comment]
Hopefully it works. Only way to know is releasing a new version I guess.

**Comment by greenmoss** [comment]
Yup. I guess I'll merge this for now.

**Comment by greenmoss** [comment]
Merged!
